### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by kyooo123** [wanzhixiao/MDL#1]
Hi thank u for your contributions on this code, i' m wondering whether this project will update?  thank u~~

**Comment by wanzhixiao** [comment]
> Hi thank u for your contributions on this code, i' m wondering whether this project will update? thank u~~

since i do not have the data, i just write this model from my understand of this paper, you can use another dataset to run this model. thanks for your attention.

**Comment by kyooo123** [comment]
i have found this dataset TaxiBJ, and i can send it to you.

**Comment by wanzhixiao** [comment]
OK, my email is xiaowanzhi@csu.edu.cn

**Comment by wanzhixiao** [comment]
But i have a concen, if the TaxiBJ dataset you said is used in STResNet, you konw. The Edge-Net in MDL model  need transition flow to construct data,but TaxiBJ dataset is an image dataset,whose shape is T×2×32x32 and only contains the in flow and out flow,and the edge net input transition flow is T×2×1024×1024，this part was processed from the raw taxi order data, not reflect in TaxiBJ.
